fix: Incorrect hanlding of ClientError raised by status()
Error 403 (due to missing token) has nothing to do with version not being supported:

% NETBOX_URL=https://demo.netbox.dev annet show device-dump dmi01-akron-rtr01
  ...
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/dataclass_rest/http/requests.py", line 19, in _on_error_default
    raise ClientError(response.status_code)
dataclass_rest.exceptions.ClientError: 403

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  ...
  File "/Users/azryve/src/github/annet/annet/adapters/netbox/provider.py", line 39, in storage_factory
    raise ValueError(f"Unsupported version: {status.netbox_version}")
                                             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'netbox_version'